powerdata <- read.delim("household_power_consumption.txt",sep = ";")
powerdatasubset <- subset(powerdata,Date %in% c("2/2/2007","1/2/2007"))
remove(powerdata)
png(filename = "plot4.png")
par(mfrow = c(2,2))
with(powerdatasubset,plot(strptime(paste(Date,Time),"%d/%m/%Y %H:%M:%S"),powerdatasubset$Global_active_power,type = "l",xlab = "",ylab = "Global Active Power (kilowatts)"))
with(powerdatasubset,plot(strptime(paste(Date,Time),"%d/%m/%Y %H:%M:%S"),Voltage,type = "l",xlab = ""))
with(powerdatasubset,plot(strptime(paste(Date,Time),"%d/%m/%Y %H:%M:%S"),powerdatasubset$Sub_metering_1,type = "n",xlab = "",ylab = "Energy sub metering"))
with(powerdatasubset,points(strptime(paste(Date,Time),"%d/%m/%Y %H:%M:%S"),powerdatasubset$Sub_metering_1,type = "l"))
with(powerdatasubset,points(strptime(paste(Date,Time),"%d/%m/%Y %H:%M:%S"),powerdatasubset$Sub_metering_2,type = "l",col = "red"))
with(powerdatasubset,points(strptime(paste(Date,Time),"%d/%m/%Y %H:%M:%S"),powerdatasubset$Sub_metering_3,type = "l",col = "blue"))
legend("topright",lwd = 1,col = c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
with(powerdatasubset,plot(strptime(paste(Date,Time),"%d/%m/%Y %H:%M:%S"),Global_reactive_power,type = "l",xlab = ""))
dev.off()